name: Feature Request
description: Suggest an idea for this project
title: "[FEAT] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving QFS x ATLAS!
        Please review the [Evergreen Roadmap](docs/QFS_ATLAS_PRODUCTION_READINESS.md) to ensure alignment.
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: dropdown
    id: capability
    attributes:
      label: Related Capability
      options:
        - Core Determinism & Crypto
        - EvidenceBus & Moderation
        - Agent Advisory Layer
        - Governance & Monetization
        - Deployment & Observability
    validations:
      required: true
  - type: textarea
    id: cost_impact
    attributes:
      label: Cost Efficiency Impact
      description: How does this align with the [Cost-Efficient Architecture](docs/COST_EFFICIENT_ARCHITECTURE.md)?
    validations:
      required: true
