"""
build_info.py - CI-Generated Build Identity
This file is auto-generated by the CI pipeline during the build process.
It contains deterministic identifiers for the code running in this artifact.
"""

import os

# CI Injection Pattern: Default safe fallback for development
# In production, CI replaces these values using sed/subst
SERVICE_NAME = os.getenv("QFS_SERVICE_NAME", "qfs-dev-local")
VERSION_TAG = os.getenv("QFS_VERSION_TAG", "v0.0.0-dev")
GIT_COMMIT = os.getenv("QFS_GIT_COMMIT", "dev-dirty")
ARTIFACT_SHA256 = os.getenv("QFS_ARTIFACT_SHA256", "sha256:dev")
BUILD_MANIFEST_SHA256 = os.getenv("QFS_BUILD_MANIFEST_SHA256", "sha256:dev-manifest")

# Manifest content
BUILD_MANIFEST = {
    "service": SERVICE_NAME,
    "version_tag": VERSION_TAG,
    "git_commit": GIT_COMMIT,
    "artifact_sha256": ARTIFACT_SHA256,
    "note": "Loaded from environment or default dev values",
}


# Identity Validation for Production
def validate_production_identity():
    """
    Ensures that for production enviroments, we are not running with placeholder values.
    """
    env = os.getenv("QFS_ENV", "development")
    if env in ["staging", "production"]:
        if "dev" in VERSION_TAG or "dev" in GIT_COMMIT:
            raise RuntimeError(
                f"FATAL: Attempting to run {env} with dev build identity: {VERSION_TAG}"
            )
