import { EnvelopeFactory } from '../src/lib/p2p/envelope';
import { hexToBytes } from '../src/lib/p2p/crypto';

async function main() {
    console.log("--- TS Envelope Verification (Cross-Language) ---");

    const walletPriv = "01".repeat(32);
    const sessionKeyHex = "000102030405060708090a0b0c0d0e0f";
    const sessionKey = hexToBytes(sessionKeyHex);

    // Envelope generated by Python script (SHA3-256 + Ascon-128 + Empty AD)
    const pythonEnvelope = {
        "space_id": "parity-test-space",
        "sender_pubkey": "0101010101010101010101010101010101010101010101010101010101010101",
        "payload_ciphertext": "7bc30e04e199fb0d5aa99de90012e0cab26064ab36f3561ef3924e7464da3d1e0e184426019130204b7761d08f163a4e6e4965d26cb233912df65e801e5213a0",
        "payload_hash": "5e78e24b1097dd5e2f836a52447dfdaf83533c092b9961c1e1b91aa6ac49390d",
        "intent": "chat.message",
        "signature": "0605c49f9d2d186240adf9e3fe4c15f3edc000011a84bfdd650b1b23e7a3cf0e1d942714d2eb43047c2c41e97230dd3aea967386974680ab3e9cfd8306990b63",
        "client_seq": 0
    };

    console.log("\n[Python Envelope Ingested]");
    console.log(`Locked Ciphertext: ${pythonEnvelope.payload_ciphertext}`);
    console.log(`Locked Hash: ${pythonEnvelope.payload_hash}`);

    const factory = new EnvelopeFactory(walletPriv);

    // Decrypt
    try {
        console.log("Attempting Decryption of Python Envelope...");
        const decrypted = await factory.decryptPayload(pythonEnvelope as any, sessionKey);
        console.log(`Decrypted Payload:`, decrypted);

        const expectedPayload = { "message": "hello world", "timestamp": 1234567890 };

        if (JSON.stringify(decrypted) === JSON.stringify(expectedPayload)) {
            console.log("SUCCESS: Python->TS Cross-Language Decryption Verified.");
        } else {
            console.error("FAILURE: Payload mismatch.");
            console.error("Expected:", expectedPayload);
            console.error("Got:", decrypted);
            process.exit(1);
        }
    } catch (e) {
        console.error("Decryption Failed:", e);
        process.exit(1);
    }
}

main().catch(console.error);
