import { EnvelopeFactory } from '../src/lib/p2p/envelope';
import { hexToBytes } from '../src/lib/p2p/crypto';

async function main() {
    console.log("--- TS Envelope Verification (Cross-Language) ---");

    const walletPriv = "01".repeat(32);
    const sessionKeyHex = "000102030405060708090a0b0c0d0e0f";
    const sessionKey = hexToBytes(sessionKeyHex);

    // Envelope generated by Python script (SHA3-256 + Ascon-128 + Empty AD)
    const pythonEnvelope = {
        "space_id": "parity-test-space",
        "sender_pubkey": "0202020202020202020202020202020202020202020202020202020202020202",
        "payload_ciphertext": "7bc30e04e199fb0d5aa99de90012e0cab26064ab36f3561ef3924e7464da3d1e0e184426019130204b7761d08f163a4e6e4965d26cb233912df65e801e5213a0",
        "payload_hash": "5e78e24b1097dd5e2f836a52447dfdaf83533c092b9961c1e1b91aa6ac49390d",
        "intent": "chat.message",
        "signature": "4c87d91a097d28ea79c695a1aaa72d7ef664914d079e4291532c69cb09d85b6db9597e2c7b8efbd420831b3b60b81777a682f2038bb44723b1cbc742dc7e3303",
        "client_seq": 0
    };

    console.log("\n[Python Envelope Ingested]");
    console.log(`Locked Ciphertext: ${pythonEnvelope.payload_ciphertext}`);
    console.log(`Locked Hash: ${pythonEnvelope.payload_hash}`);

    const factory = new EnvelopeFactory(walletPriv);

    // Decrypt
    try {
        console.log("Attempting Decryption of Python Envelope...");
        const decrypted = await factory.decryptPayload(pythonEnvelope as any, sessionKey);
        console.log(`Decrypted Payload:`, decrypted);

        const expectedPayload = { "message": "hello world", "timestamp": 1234567890 };

        if (JSON.stringify(decrypted) === JSON.stringify(expectedPayload)) {
            console.log("SUCCESS: Python->TS Cross-Language Decryption Verified.");
        } else {
            console.error("FAILURE: Payload mismatch.");
            console.error("Expected:", expectedPayload);
            console.error("Got:", decrypted);
            process.exit(1);
        }
    } catch (e) {
        console.error("Decryption Failed:", e);
        process.exit(1);
    }
}

main().catch(console.error);
